### ISSUE TITLE
BUG in Teacher Tools: Topic Selection/elimination

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#306] opened 2016-11-30 15:54 UTC
Hi Rafael,

Eliminating a topic for class: Hannen Green
(teacher Hannen/HannenG)
gives an exception:

Duplicate entry '1279--1-12' for key 'PRIMARY'
Cannot remove any topics just for that class.

--Ivon

**Comment by IvonArroyo** [comment] 2016-11-30 16:04
![screen shot 2016-11-30 at 11 04 03 am](https://cloud.githubusercontent.com/assets/5631787/20760041/c3acbe4a-b6ec-11e6-95f9-8fc19cebafcd.png)

**Comment by IvonArroyo** [comment] 2016-11-30 16:04
I will edit now by hand, but you can see the problem

**Comment by rezecib** [comment] 2016-12-01 05:02
I've been looking into this... I see that the issue is that somehow it's listing a lot of topics as being both disabled and enabled. This was possible from the database side in the first place because the primary key for that table is the tuple of (classId, seqPos, probGroupId), when really it should just be (classId, probGroupId)-- that way that pairing can only occur once in the table, and therefore has only one seqPos (-1 for disabled, positive for enabled). Changing the primary key to this more restrictive tuple will mean that instead of an error occurring after the table is "broken", it will throw an error when it tries to make the illegal change in the first place, which should let you keep doing other changes.

That being said, I don't know how this happened from the Java side, and couldn't get it to happen on my test server-- I tried a bunch of steps removing and adding topics, including removing all topics and then adding some back in and removing again.

@marshall62 :

I want to change the table to use the more restrictive primary key, but it looks like there are a lot of duplicate rows like that in there now. I'm guessing that the right thing to do is to remove the rows that specify them as disabled, keeping the enabled position rows.

I also noticed that some classes seem to be missing certain topics entirely, and that this is handled perfectly by the topic selection page-- it just checks which topics are active. So it seems like the way to go would actually be to remove ALL rows that specify -1 as the topic position, since those rows really aren't needed, and just add a little bloat and slowdown.

**Comment by marshall62** [comment] 2016-12-01 13:34
I agree with you about removing the seqPos from the primary key.  Not sure
why I did that.  You'd have to delete rows that violate this.  Who knows
how they were created?   Someone may have hand-entered.

On Thu, Dec 1, 2016 at 12:02 AM, Rafael Lizarralde <notifications@github.com

**Comment by IvonArroyo** [comment] 2016-12-01 18:57
Hi all,

My graduate student Naomi Wixon did it with some combination of actions
from the teacher tools, I don't know exactly how she did it, but did not
access the DB directly.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by rezecib** [comment] 2017-02-10 21:04
This should be fixed with the next release, but I'm going to leave this open as a reminder that I need to clean that table after the release.

**Comment by rezecib** [comment] 2017-03-02 21:24
Database is cleaned, primary key changed, and the underlying problem should be fixed.

**Closed by rezecib** 2017-03-02 21:24 UTC
Labels: teacher tools
