### ISSUE TITLE
Bug in LOGS, or but in Problem?

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#327] opened 2017-02-10 17:57 UTC
See attached screenshot.

I don’t know if this is a bug in the problem or in the Logs. There is a zero (0) recorded in isCorrect, this means a new incorrect attempt, but this is immediately after a correct attempt was made. This is for problem 1061.

<img width="1190" alt="buginproblem" src="https://cloud.githubusercontent.com/assets/5631787/22837876/75051512-ef90-11e6-885c-f6a2018a163c.png">

**Comment by marshall62** [comment] 2017-02-10 18:22
When an incorrect attempt (E) is made after a correct attempt (A), the log shows isCorrect=0 to indicate that the E attempt was wrong.  The studentproblemhistory table shows the correct stats for this problem :  that it solved correctly in 2 attempts.  

We could change the logging to show attempts that come in after the problem is solved be marked as isCorrect=1 but that might seem confusing.    You decide and I'll make it work that way.

**Comment by marshall62** [comment] 2017-02-14 23:55
Since I haven't heard a reply I'm going to assume you weren't happy with problems being marked isCorrect=0 after they were solved.   So I've changed the logging to set isCorrect=1 for all attempts made on the problem after it has been solved.

**Closed by marshall62** 2017-02-14 23:55 UTC
