### ISSUE TITLE
Examples don't show the last hint?

### ISSUE THREAD

**Issue by IvonArroyo** [marshall62/mathspring#184] opened 2015-04-07 16:58 UTC
Hi, I realized that the examples don't show the last hint? Is this possible?

The whole point of an example is that it shows you all the steps.

--Ivon

**Comment by IvonArroyo** [comment] 2015-04-07 17:17
Maybe only HTML problems?

**Comment by marshall62** [comment] 2015-04-07 18:14
I just looked at 5 example problems all of which showed the answer.   Can you be more specific about what topic you are in or what problem you are in when you see the example so that I can reproduce this.   It may be that the person did not author the final calculation of the answer into the last hint so we need to know the problem id of the example so we can see how it was authored.

**Comment by marshall62** [comment] 2015-05-14 15:43
I'm not hearing back from you when I post follow-ups to your gitHub issues.   Are you getting emails?

If a hint is marked as givesAnswer=1 then these hints do not show up because the tutor does not even read them in.    People have confusion about this.   We used to mark hints that said "Choose C" as gives answer=1 and it made sense to stop giving them.   Recently people may be building hints that have meaningful math in them including the solution and then mark them as givesAnswer=1.   But these are not going to show up.

**Comment by IvonArroyo** [comment] 2015-05-14 18:10
Hi David,

Sometimes I don't answer because I am super busy, or sometimes because I
think it might be better to talk about this during the next meeting.

" If a hint is marked as givesAnswer=1 then these hints do not show up
because the tutor does not even read them in. "

They should be read in for example problems, but not for practice problems.
Most of the times the last hint does not only include the answer but other
stuff, that should help to solve the problem. If this gets cut off, then
the example doesn't make sense any more.

A worked out example should get you all the way to the last hint, they
should be read in by the system, and ignored for the practice problems only.

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by marshall62** [comment] 2015-05-14 18:19
We used to have many problems that had a hint of "choose C".   Those were
found to be unacceptable so we marked them as givesAnswer=1 so they
wouldn't show up anymore.   Now people are building hints that have math in
them and show other useful things and are marking them givesAnswer=1.
For the purposes of the studentModel we want to know if the student saw a
hint that gave them the answer so that's why they must do it.   I'm afraid
there isn't a solution using this one flag.

I think we are going to need a new flag like isOff.   We can set the hints
that are like Choose C to isOff=true and then we won't return those in any
situation.   The hints marked givesAnswer=1 will then be returned in both
problems and examples.

Is this what you want?

**Comment by IvonArroyo** [comment] 2015-05-14 20:14
Of course that now that I am looking for a problem that has that issue, now
I cannot find any…

Let's hold back until I can find a problem that shows the issue…. let's
talk at the meeting.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by IvonArroyo** [comment] 2015-05-14 20:26
Hi Ivon,

For practice problems, wouldn’t best case scenario be for students to have the option whether to see the answer hint?  I thought that was what you wanted.

It seems as though this could be accomplished two ways, either by having a separate button that plays that hint, the way you did in the old system, or having the hints labelled so that the student knows when to stop clicking the Hint button.

If you are looking for Flash problems that have useful math content in their Answer hints, I know that many of Elizabeth’s do.

—Lynn

-----------------
Lynn Stephens
Post Doctoral Researcher
School of Computer Science  and 
College of Education
University of Massachusetts—Amherst
(413) 230-4634

**Comment by IvonArroyo** [comment] 2015-05-14 22:18
Hi Lynn,

We were talking about the "example" problems, those should have the last
hint included, especially  if it involves some part of the explanation.  I
saw some problems getting cut off, and not showing the last hint in the
examples.

But now I cannot find which those specific problems were. I will keep
looking.

--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Comment by IvonArroyo** [comment] 2015-05-26 19:56
Let's close this isse for the time being, I haven't been able to replicate
the issue.

Maybe it was a bug on a couple of problems themselves and not in the system.
--Ivon

-----------
Ivon Arroyo
Assistant Professor
Learning Sciences and Technologies
Social Sciences and Policy Studies
Salisbury Labs 317A
Worcester Polytechnic Institute

**Closed** 2016-06-08 16:18 UTC
